### ISSUE TITLE
build  fail

### ISSUE THREAD

**Issue by guleng** [keedio-sense/cloudera_exporter#1]
make local_build

go: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
go: finding github.com/go-kit/kit v0.8.0
go: golang.org/x/net@v0.0.0-20181201002055-351d144fa1fc: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20181114220301-adae6a3d119a: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/davecgh/go-spew v1.1.1
go: golang.org/x/sys@v0.0.0-20181116152217-5ac8a444bdc5: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20180905080454-ebe1bf3edb33: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/crypto@v0.0.0-20180904163835-0709b304e793: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: error loading module requirements
Makefile.common:79: recipe for target 'build_in_local' failed
make: *** [build_in_local] Error 1

**Comment by r2dedios** [comment]
Hi guleng,

Thanks for the issue. I'm going to review it

**Comment by guleng** [comment]
thanks @r2dedios  It's a matter that packages can't be downloaded.
It is OK now！

**Comment by r2dedios** [comment]
Ok Guleng,

Thanks
