### ISSUE TITLE
 Invalid HTTP response code: 401 Bad credentials for the request

### ISSUE THREAD

**Issue by guleng** [keedio-sense/cloudera_exporter#2]
[ERROR] [KBDI] 2019/07/04 20:13:38 common_module.go:100:  Invalid HTTP response code: 401 Bad credentials for the request: http://manage20.aibee.cn:7180/api/v30/cm/version
[ERROR] [KBDI] 2019/07/04 20:13:38 common_module.go:100:  Invalid HTTP response code: 401 Bad credentials for the request: http://manage20.aibee.cn:7180/api/v30/clusters
[ERROR] [KBDI] 2019/07/04 20:13:38 common_module.go:100:  Invalid HTTP response code: 401 Bad credentials for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(dfs_capacity)+WHERE+category=SERVICE
[WARN]  [KBDI] 2019/07/04 20:13:38 Dont Have specific queries for Cloudera Manager version 
[ERROR] [KBDI] 2019/07/04 20:13:38 common_module.go:100:  Invalid HTTP response code: 401 Bad credentials for the request: http://manage20.aibee.cn:7180/api/v30/hosts

my  cloudera CDH 6.0.1

**Comment by r2dedios** [comment]
Did you update the config.ini file with your Cloudera user credentials?

**Comment by guleng** [comment]
yes .   I wrote the username password to config.ini

**Comment by r2dedios** [comment]
Try to run the following command in the same machine where you run the Cloudera Exporter:

`sh
curl -u <CLOUDERA_USER>:<CLOUDERA_PASSWD>  http://manage20.aibee.cn:7180/api/v30/hosts
`

If the curl returns the same error, you are using invalid credentials

**Comment by guleng** [comment]
I changed my admin account to see some, but some returned 500 errors.

[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_admission_wait_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_hdfs_bytes_read_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_hdfs_bytes_written_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_bytes_streamed_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_cm_cpu_milliseconds_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_query_duration_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_memory_accrual_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_memory_spilled_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:100:  Invalid HTTP response code: 500 Server Error for the request: http://manage20.aibee.cn:7180/api/v30/timeseries?query=SELECT+LAST(INTEGRAL(impala_query_thread_cpu_time_rate))+WHERE+serviceType+=+"IMPALA"
[ERROR] [KBDI] 2019/07/05 19:56:02 common_module.go:297:  Error making query: Invalid HTTP response code

**Comment by guleng** [comment]
ok
