### ISSUE TITLE
Do you support HTTPS authentication?

### ISSUE THREAD

**Issue by guleng** [keedio-sense/cloudera_exporter#3]
Do you support HTTPS authentication?

Because my CDH has autotls!

**Comment by r2dedios** [comment]
Hi,

At the moment is not supported TLS. Is one of the new features we want to develop.

**Comment by guleng** [comment]
Ok I hope to see the new version soon. Thank you!

**Comment by r2dedios** [comment]
If you want to help us with this development we will be grateful
